fix: Diverse ReadMe utility fixes (#1768)
## Description

- Updated path regex to search for 'avm/res|ptn` instead of only `avm`
to allow the folder name `avm` in other parts of file paths
- Have readme utility ignore commented lines found in the
`testDeployment` params block
- Have readme utility throw an exception if any parameter in the
processed template files does not contain the required category (e.g.,
'Required.') in its description to avoid misleading sideeffects

Reran utility across all templates... which as expected did not cause
any changes

```
Example output for incorrect parameters:
========================================
Exception: C:\dev\ip\\avm\utilities\pipelines\sharedScripts\Set-ModuleReadMe.ps1:260:9
Line |
 260 |          throw ("Each parameter description should start with a catego …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Each parameter description should start with a category like [Required. / Optional. / Conditional. ]. The following parameters are missing such a category:  [{"name":"name","description":"Name of the 
     | Key Vault. Must be globally unique."},{"name":"secrets","description":"All secrets to create."}]Branch : users/alsehr/1761_readMeSupportComments
```

## Pipeline Reference

<!-- Insert your Pipeline Status Badge below -->

| Pipeline |
| -------- |
|
[![avm.res.key-vault.vault](https://github.com/AlexanderSehr/bicep-registry-modules/actions/workflows/avm.res.key-vault.vault.yml/badge.svg?branch=users%2Falsehr%2F1761_readMeSupportComments)](https://github.com/AlexanderSehr/bicep-registry-modules/actions/workflows/avm.res.key-vault.vault.yml)
|

## Type of Change

<!-- Use the check-boxes [x] on the options that are relevant. -->

- [x] Update to CI Environment or utlities (Non-module effecting
changes)
- [ ] Azure Verified Module updates:
- [ ] Bugfix containing backwards compatible bug fixes, and I have NOT
bumped the MAJOR or MINOR version in `version.json`:
- [ ] Someone has opened a bug report issue, and I have included "Closes
#{bug_report_issue_number}" in the PR description.
- [ ] The bug was found by the module author, and no one has opened an
issue to report it yet.
- [ ] Feature update backwards compatible feature updates, and I have
bumped the MINOR version in `version.json`.
- [ ] Breaking changes and I have bumped the MAJOR version in
`version.json`.
  - [ ] Update to documentation

---------

Co-authored-by: Erika Gressi <56914614+eriqua@users.noreply.github.com>